Map generation
duquevieira/Tales pull request #115
Opened 2023-07-18 20:17 UTC by andreauxtero

2023-07-18 21:25 UTC, DuarteFGuerreiro commented on Assets/Scripts/Object Classes/Object.cs
nomes das variaveis, a, n1,n2, etc

2023-07-18 21:28 UTC, DuarteFGuerreiro commented on Assets/Scripts/Story/StoryEngineScript.cs
apaga os comentarios que eu ja adicionei o itemsmanager à createscene

2023-07-18 21:29 UTC, DuarteFGuerreiro commented on Assets/Scripts/UI/PrefabMenuScript.cs
o folders to search é um vetor, podes ter la varios folders para dar display dos assets e da-me jeito ter os do trainingset de momento

2023-07-18 21:29 UTC, DuarteFGuerreiro requested changes
ver comentarios individuais

2023-07-18 22:05 UTC, Daniel-Gavinho requested changes
Talvez seja melhor trocar o nome do script Object.cs tendo em conta que isso é uma palavra reservada, a não ser que isso seja intencional

2023-07-18 22:10 UTC, DuarteFGuerreiro approved these changes

2023-07-19 09:03 UTC, Daniel-Gavinho approved these changes

2023-07-19 11:29 UTC, merged