Loading screen level-database
duquevieira/Tales pull request #28
Opened 2023-03-22 10:17 UTC by Daniel-Gavinho

-Loading Screen
-Simple Level data structure
-Working Load Screen
-Uniting everything in one scene

2023-03-25 13:05 UTC, DuarteFGuerreiro commented on Assets/Scripts/LoadList.cs
Tu estás a associar o sceneID ao id que recebes sempre podes ter isso só numa linha de código antes do if e do else em vez de fazeres o mesmo código duas vezes (linhas 16 e 21) e depois devias usar referencia ao sceneID em vez do id (linha 23).

Inicializa a lista "levels" no método Start.

Eu não sei exatamente como é que funcionam alguns métodos que tu tens aqui mas fazes muitos cálculos com números arbitrários (+2, %3, *3, etc) não seria mais fácil para ti criares algumas constantes (caso sejam constantes ou variáveis se dependerem do número de objetos que possam existir) para ser mais fácil alterares estes métodos no futuro sem te enganares?

2023-03-25 13:12 UTC, DuarteFGuerreiro commented on Assets/Scripts/SceneSwitcher.cs
Se utilizares "[SerializeField]" antes das tuas variáveis públicas (main e load) depois podes mudá-las para sendo privadas e consegues associá-las na mesma no editor

2023-03-25 13:13 UTC, DuarteFGuerreiro requested changes
Lê os meus comentários ao "LoadList" e "SceneSwitcher" :)

2023-03-26 18:09 UTC, DuarteFGuerreiro approved these changes

2023-04-18 21:20 UTC, andreauxtero approved these changes

2023-04-18 21:20 UTC, merged