Save and Load added and Main menu bugs fixed
duquevieira/Tales pull request #63
Opened 2023-05-11 19:14 UTC by Daniel-Gavinho

-Added a Save to JSON file (Currently to Desktop)
-Added a Load function that reads the JSON File
-Fixed the animations on the main menu not working when returning -Fixed Menus not disappearing when loading a Level

2023-05-12 13:11 UTC, DuarteFGuerreiro commented on Assets/Scripts/LoadMenuScript.cs
loadingBar tem letra minúscula

2023-05-12 13:17 UTC, DuarteFGuerreiro commented on Assets/Scripts/Records/Tale.cs
propDataList e playerPos minúsculos

2023-05-12 13:19 UTC, DuarteFGuerreiro requested changes
vê os comentários 👍

2023-05-16 17:45 UTC, andreauxtero approved these changes

2023-05-18 16:02 UTC, DuarteFGuerreiro approved these changes

2023-05-18 16:03 UTC, merged